### PR TITLE
Update 19 - Pull request guidelines

### PR DESCRIPTION
**Pull request by VaclavElias**

### CODE REVIEW

**Review by ykafia — COMMENTED** [review]
LGTM! I have not much to say

**Review by Kryptos-FR — COMMENTED** [review]
I think a few screenshots of either past PRs or a fake one to illustrate what the rules mean could help.

Aside from that, LGTM.

**Comment by VaclavElias** [comment]
> I think a few screenshots of either past PRs or a fake one to illustrate what the rules mean could help.
> 
> Aside from that, LGTM.

Hmm, let me think what I can come up with.

**Comment by VaclavElias** [comment]
Let me get this to staging for the next review.

**Comment by VaclavElias** [comment]
@Kryptos-FR, I have listed some fake examples here https://stride-doc-staging.azurewebsites.net/latest/en/contributors/contribution-workflow/github-pull-request-guidelines.html#examples

**Pull request merged**
