### PR TITLE
feat: Add documentation on Flexible Processing

### PR DESCRIPTION
**Pull request by Eideren**
Docs for PR https://github.com/stride3d/stride/pull/2331
Not sure that's all I need to do to create this new page ... I forgot ? Also not sure how xrefs work for types with generic arguments ?

### CODE REVIEW

**Comment by VaclavElias** [comment]
It should be all. Unless we want to link it from multiple places and add some intro context:

- https://doc.stride3d.net/latest/en/manual/engine/index.html
- https://doc.stride3d.net/latest/en/manual/engine/entity-component-system/index.html

Regarding `xref`, I usually take it from the browser F12, `data-uid` attribute (once that API was published 🤣) but I can fix that for you.

Would you like to add more content to the pages mentioned above? If not, I will deploy it to staging and we can assess further text and styling.

Example of finding xref:

image

**Comment by VaclavElias** [comment]
Actually, in this case, it would be good to mention it also here in the Recent Updates https://doc.stride3d.net/latest/en/manual/index.html

**Comment by Eideren** [comment]
> Would you like to add more content to the pages mentioned above?
No other page mentions `Managing Entities` so I didn't really think of linking this one either, it's a bit niche

**Comment by VaclavElias** [comment]
No problem. The manual home page should bring some awareness at least.

**Comment by VaclavElias** [comment]
Thank you for the updates.

**Pull request merged**
