### PR TITLE
Update install stride page

### PR DESCRIPTION
**Pull request by Kryptos-FR**
- new screenshots based on latest version
- change image format to WebP

Fixes first task of #219

### CODE REVIEW

**Comment by VaclavElias** [comment]
Thanks @Kryptos-FR.

This file `install-stride.md`, point 12. Shall we mention, that image is just for illustration purpose and it can be any latest .NET SDK, mentioned in prerequesites?

The bottom part Note needs to be fixed, probably there shouldn't be an empty line. Here are the examples: https://dotnet.github.io/docfx/docs/markdown.html?tabs=linux%2Cdotnet#alerts

image

**Comment by VaclavElias** [comment]
And point 9, there is a typo `pricay policy`, should be `privacy policy`?

**Comment by Kryptos-FR** [comment]
Fixing the typo and the note. I don't think we need to specify images are for illustration, it's kind of implicit.

**Review by VaclavElias — APPROVED** [review]
Thank you. I checked it on my PC and it seems all ok :)

**Comment by VaclavElias** [comment]
> I don't think we need to specify images are for illustration, it's kind of implicit.

That is true.

**Pull request merged**
