### PR TITLE
update API doc gen formatting , add a custom mesh draw example

### PR DESCRIPTION
**Pull request by jeske**
This changes the class gen pages to

a. include inherited members
b. put all summaries at the top, and all details at the bottom
c. clean up the formatting a little, in the spirit of Microsoft docs

I also have the lingering custom triangle draw example that got piled in there.

The top section now looks more like the MS docs....

image

There is a single "summary" block at the top that summaries Constructors, Properties, and Methods in one table.

image

And at the bottom, the "InheritedMembers" list is restored from the default DocFx templates. (it was removed for some reason)

image

### CODE REVIEW

**Comment by jeske** [comment]
resolves...

https://github.com/stride3d/stride-docs/issues/34
https://github.com/stride3d/stride-docs/issues/33

**Comment by jeske** [comment]
oops, i just noticed (see first screenshot) that the button class description is repeated twice...

**Comment by Kryptos-FR** [comment]
I think the "inherited members" section was removed because it was creating a lot of noise as we have some deep inheritance hierarchy in some cases.

I understand from #33 why having them back would be good. However, I think we could consider modifying the theme to have that section collapsible ("collapsed" by default). Otherwise, one need to scroll down quite a bit to pass that section.

**Comment by jeske** [comment]
I put it at the bottom so there is nothing past the inherited members section...

It needs to be uncollapsed for easy control-F find in page

**Comment by xen2** [comment]
Thanks!

**Pull request merged**
