### PR TITLE
[WIP] Bepu physics manual 

### PR DESCRIPTION
**Pull request by Nicogo1705**
Stated to write some documentation about bepu physics.
Based on my [WIKI](https://github.com/Nicogo1705/Stride.BepuPhysics/wiki)

### CODE REVIEW

**Comment by Nicogo1705** [comment]
@dotnet-policy-service agree

**Comment by Eideren** [comment]
I'm also working on a couple of docs, how should we do this @VaclavElias ? Should we merge every PR asap so we can all work off of that branch directly ?

Regarding describing properties, I think it's fine to link to the API directly instead, a bit redundant and might get out of date otherwise.
If the API is not descriptive enough might as well extend those descriptions with `<remarks/>` and `<userdoc>`

**Comment by VaclavElias** [comment]
Yes, good idea! I think you can go ahead and merge these in your convenience (don't wait when I am available) becuase it is all isolated in the Physics folder, it won't affect other pages (at the moment) so I don't have to review for potential issues.

Also, so we have some structure, don't worry about details, we can polish content/links/API collectively anytime we can read/review your new content :)

The level of details we can go simply to start with as you suggested linking to the API directly. Again, later in the next phase we can elaborate futher and more in docs.

**Comment by VaclavElias** [comment]
Just a side note, you can leave it with me, we should preserve the old pages for example this one was deleted (en/manual/physics/collider-shapes.md) because it is indexed by Google (search engines). If we aren't going to use it for Bepu, we can repurpose that page, de-linking from the Bepu content and just add some content directing to Bepu.

**Pull request merged**
