### PR TITLE
Added editor video tutorials

### PR DESCRIPTION
**Pull request by Aggror**
I have added the (old) game studio video tutorials to the tutorials section.

Note: I was not able to build the documentation manually yet, hence it is a draft.

### CODE REVIEW

**Comment by tebjan** [comment]
great, this works! only one thing: 
image

the note boxes are not parsed, somehow...

**Comment by tebjan** [comment]
fixed that and merged it, thanks!

**Comment by Aggror** [comment]
Thanks @tebjan for checking the results. Did the local website run without any issues for you? Maybe my local setup was just wrong.

**Comment by tebjan** [comment]
it worked without issues, I've first run the build.bat file and the run_local_website.bat file.

**Pull request merged**
